#include "tss.h"

#define TSS_COUNT 3
/*
 * Arreglo de TSSs 
 * TODO: Completar el resto de las TSSs
 */
tss tsss[TSS_COUNT] = {
	// este es el contexto de la tarea del kernel
	(tss) {
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short)  0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0
	},

	// este es el contexto del traductor
	(tss) {
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short)  0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0
	}, 

	// este es el contexto del pintor
	(tss) {
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short)  0,
		(unsigned int) 0,
		(unsigned short) 0,
		(unsigned short) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned int) 0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0,
		(unsigned short)  0
	}
	
};
